### ISSUE TITLE
Authenticate gcloud

### ISSUE THREAD

**Issue by LMSSonos** [nexsolab/azure-devops-google-cloud-tools#14]
Hello

After installing gcloud I want to execute custom commands. I did not find out how I can use the service connection to authenticate for using my custom glcoud commands.

Thanks

**Comment by gcacars** [comment]
Hi @LMSSonos , sorry for the late reply (I was on vacation :))
You must place the contents of your JSON credentials file in the text box.
It's documented in [Configure Azure DevOps Service Connection to Google Cloud](https://github.com/nexsolab/azure-devops-google-cloud-tools/blob/master/SERVICECONN.md) in the section [Service Connection](https://github.com/nexsolab/azure-devops-google-cloud-tools#service-connection) of the Readme.
Let me know if it helped you.

**Comment by LMSSonos** [comment]
Thanks @gcacars - that helped and works now
