### ISSUE TITLE
Facing issue while deploying cloud function 

### ISSUE THREAD

**Issue by teja14312** [nexsolab/azure-devops-google-cloud-tools#54]
Hello, I'm trying to run a azure pipeline job, but it crashes at a point when it says "Uploading source code file" in the second run build. The first build updated fine, and the job ran for more than 50 minutes.

![image](https://user-images.githubusercontent.com/24800907/155282143-011ff555-a3f0-45ed-b3e4-aa4319cb70b5.png)

**Comment by teja14312** [comment]
resolved

**Comment by teja14312** [comment]
Hello, I'm trying to run a azure pipeline job, but it crashes at a point when it says "Uploading source code file" in the second run build. The first build updated fine, and the job ran for more than 50 minutes.

![image](https://user-images.githubusercontent.com/24800907/155521131-4ea36abd-de5c-4288-ae59-c7d0bb8975f1.png)

**Comment by gcacars** [comment]
Hi @teja14312 , please [enable debug](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops) option when you run your pipeline and check the complete log.
